---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-operator-customer
  namespace: monitoring-system
data:
  values.yaml: |
    grafana:
      config:
        auth.generic_oauth:
          role_attribute_path: contains(groups[*], 'schiff-readonly') && 'Viewer' || contains(groups[*], 'schiff-admin') && 'Admin' || contains(groups[*], 'schiff-emergency') && 'Admin' || contains(groups[*], 'customer-shortname-poweruser') && 'Admin' || contains(groups[*], 'customer-shortname-collaborator') && 'Editor' || contains(groups[*], 'customer-shortname-readonly') && 'Viewer'
          allowed_domains: das-schiff.io
