---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: node-exporter
  namespace: kube-system
spec:
  releaseName: node-exporter
  interval: 5m
  chart:
    spec:
      chart: node-exporter
      version: '2.2.x'
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: schiff-system
      interval: 1m
  valuesFrom:
  - kind: ConfigMap
    name: node-exporter-default
  - kind: ConfigMap
    name: node-exporter-environment
    optional: True
  - kind: ConfigMap
    name: node-exporter-site
    optional: True
  - kind: ConfigMap
    name: node-exporter-customer-default
    optional: True
  - kind: ConfigMap
    name: node-exporter-customer
    optional: True
  - kind: ConfigMap
    name: node-exporter-cluster
    optional: True
