---
apiVersion: v1
kind: ConfigMap
metadata:
  name: metallb-environment
  namespace: metallb-system
data:
  values.yaml: |
    prometheusRule:
      enabled: true
    controller:
      prometheus:
        serviceMonitor:
          enabled: true
      resources:
      # We usually recommend not to specify default resources and to leave this as a conscious
      # choice for the user. This also increases chances charts run on environments with little
      # resources, such as Minikube. If you do want to specify resources, uncomment the following
      # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
        limits:
          cpu: 20m
          memory: 50Mi
        requests:
          memory: 25Mi
          cpu: 15m

    speaker:
      prometheus:
        serviceMonitor:
          enabled: true	
      resources:
      # We usually recommend not to specify default resources and to leave this as a conscious
      # choice for the user. This also increases chances charts run on environments with little
      # resources, such as Minikube. If you do want to specify resources, uncomment the following
      # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
        limits:
          cpu: 150m
          memory: 250Mi
        requests:
          memory: 100Mi
          cpu: 100m