---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-ingress-controller-environment
  namespace: ingress-system
data:
  values.yaml: |
    resources:
      # We usually recommend not to specify default resources and to leave this as a conscious
      # choice for the user. This also increases chances charts run on environments with little
      # resources, such as Minikube. If you do want to specify resources, uncomment the following
      # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
      limits:
        cpu: 1
        memory: 2000Mi
      requests:
        cpu: 250m
        memory: 256Mi
    containerSecurityContext:
      allowPrivilegeEscalation: false
    defaultBackend:
      resources:
        # We usually recommend not to specify default resources and to leave this as a conscious
        # choice for the user. This also increases chances charts run on environments with little
        # resources, such as Minikube. If you do want to specify resources, uncomment the following
        # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
        limits:
          cpu: 100m
          memory: 60Mi
        requests:
          cpu: 20m
          memory: 10Mi
      containerSecurityContext:
        enabled: true
        runAsUser: 1001
        runAsNonRoot: true
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]
