---
apiVersion: v1
kind: ConfigMap
metadata:
  name: node-feature-discovery-environment
  namespace: node-feature-discovery
data:
  values.yaml: |
    master:
      resources:
        limits:
          cpu: 100m
          memory: 128Mi
        requests:
          cpu: 100m
          memory: 128Mi
    worker:
      resources:
        limits:
          cpu: 100m
          memory: 128Mi
        requests:
          cpu: 100m
          memory: 128Mi