apiVersion: apps/v1
kind: Deployment
metadata:
  name: source-controller
  namespace: flux-system
spec:
  template:
    spec:
      containers:
      - name: manager
        resources:
          limits:
            cpu: 2500m
            memory: 2Gi
          requests:
            cpu: 1000m
            memory: 1Gi
      hostAliases:
      - hostnames:
        - harbor.das-schiff-legacy.io
        ip: <ip:ip_address>
