apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/instance: kube-prometheus
    app.kubernetes.io/name: prometheus
    statefulset.kubernetes.io/pod-name: prometheus-prometheus-prometheus-1
  name: prometheus-1
  namespace: monitoring-system
spec:
  ports:
  - name: web
    port: 9090
    protocol: TCP
    targetPort: web
  selector:
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/instance: prometheus-prometheus
    app.kubernetes.io/name: prometheus
    prometheus: prometheus-prometheus
    statefulset.kubernetes.io/pod-name: prometheus-prometheus-prometheus-1
  sessionAffinity: ClientIP
  type: ClusterIP
