---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kyverno-default
  namespace: kyverno
data:
  values.yaml: |
    replicaCount: 1
    podSecurityStandard: custom
    resources:
      limits:
        memory: 1Gi
      requests:
        cpu: 600m
        memory: 300Mi