---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-ingress-controller-management-default
  namespace: ingress-system
data:
  values.yaml: |
    service:
      ports:
        http: 8080
        https: 8443
    ingressClass: management-system