---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rbac-manager-default
  namespace: rbac-system
data:
  values.yaml: |
    image:
      pullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 200m
        memory: 128Mi
      limits:
        cpu: 400m
        memory: 256Mi
    serviceMonitor:
      enabled: true