apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-operator-environment
  namespace: monitoring-system
data:
  values.yaml: |
    grafana:
      resources:
        limits:
          cpu: 2000m
          memory: 2000Mi
        requests:
          cpu: 100m
          memory: 200Mi