---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring-system
  labels:
    name: monitoring-system
    platform.das-schiff.io/name: monitoring-system
    owner: das-schiff
    platform.das-schiff.io/owner: das-schiff
