---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: alertmanager
  namespace: monitoring-system
spec:
  releaseName: alertmanager
  interval: 5m
  install:
    skipCRDs: true
  chart:
    spec:
      chart: kube-prometheus
      version: '4.1.x'
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: schiff-system
      interval: 1m
  valuesFrom:
  - kind: ConfigMap
    name: alertmanager-default
  - kind: ConfigMap
    name: alertmanager-environment
    optional: true
  - kind: ConfigMap
    name: alertmanager-site
  - kind: ConfigMap
    name: alertmanager-customer-default
    optional: true
  - kind: ConfigMap
    name: alertmanager-customer
    optional: true
  - kind: ConfigMap
    name: alertmanager-cluster
    optional: true
