apiVersion: v1
data:
  calico_backend: bird
  cni_network_config: "{\n  \"name\": \"k8s-pod-network\",\n  \"cniVersion\": \"0.3.1\"\
    ,\n  \"plugins\": [\n    {\n      \"type\": \"calico\",\n      \"log_level\":\
    \ \"info\",\n      \"log_file_path\": \"/var/log/calico/cni/cni.log\",\n     \
    \ \"datastore_type\": \"kubernetes\",\n      \"nodename\": \"__KUBERNETES_NODE_NAME__\"\
    ,\n      \"mtu\": __CNI_MTU__,\n      \"ipam\": {\n          \"type\": \"calico-ipam\"\
    \n      },\n      \"policy\": {\n          \"type\": \"k8s\"\n      },\n     \
    \ \"kubernetes\": {\n          \"kubeconfig\": \"__KUBECONFIG_FILEPATH__\"\n \
    \     }\n    },\n    {\n      \"type\": \"portmap\",\n      \"snat\": true,\n\
    \      \"capabilities\": {\"portMappings\": true}\n    },\n    {\n      \"type\"\
    : \"bandwidth\",\n      \"capabilities\": {\"bandwidth\": true}\n    }\n  ]\n}"
  typha_service_name: none
  veth_mtu: '0'
kind: ConfigMap
metadata:
  name: calico-config
  namespace: kube-system
