apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: prometheus-thanos
  namespace: monitoring-system
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: grafana
spec:
  name: prometheus-thanos.yaml
  datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      url: http://thanos-query-frontend.monitoring-system.svc:9090
      isDefault: true
      version: 1
      editable: false
      jsonData:
        tlsSkipVerify: true
        timeInterval: "5s"