---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rbac-manager
  namespace: rbac-system
spec:
  releaseName: rbac-manager
  interval: 5m
  chart:
    spec:
      chart: rbac-manager
      version: '1.8.x'
      sourceRef:
        kind: HelmRepository
        name: schiff-meta
        namespace: schiff-system
      interval: 1m
  valuesFrom:
    - kind: ConfigMap
      name: rbac-manager-default
