apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-controller
  namespace: flux-system
spec:
  template:
    spec:
      hostAliases:
      - hostnames:
        - harbor.das-schiff-legacy.io
        ip: <ip:ip_address>