---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana-operator
  namespace: monitoring-system
spec:
  releaseName: grafana-operator
  interval: 5m
  install:
    skipCRDs: true
  dependsOn:
    - name: prometheus-operator
  chart:
    spec:
      chart: grafana-operator
      version: '0.6.x'
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: schiff-system
      interval: 1m
  valuesFrom:
  - kind: ConfigMap
    name: grafana-operator-default
  - kind: ConfigMap
    name: grafana-operator-environment
    optional: true
  - kind: ConfigMap
    name: grafana-operator-site
    optional: true
  - kind: ConfigMap
    name: grafana-operator-customer-default
    optional: true
  - kind: ConfigMap
    name: grafana-operator-customer
    optional: true
  - kind: ConfigMap
    name: grafana-operator-cluster
