---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: monitoring-system
spec:
  releaseName: prometheus
  interval: 5m
  install:
    skipCRDs: true
  chart:
    spec:
      chart: kube-prometheus
      version: '4.3.x'
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: schiff-system
      interval: 1m
  valuesFrom:
  - kind: ConfigMap
    name: prometheus-default
  - kind: ConfigMap
    name: prometheus-environment
    optional: True
  - kind: ConfigMap
    name: prometheus-site
    optional: True
  - kind: ConfigMap
    name: prometheus-customer-default
    optional: true
  - kind: ConfigMap
    name: prometheus-customer
    optional: true
  - kind: ConfigMap
    name: prometheus-cluster
    optional: true
