---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: thanos
  namespace: monitoring-system
spec:
  releaseName: thanos
  interval: 5m
  chart:
    spec:
      chart: thanos
      version: '3.16.x'
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: schiff-system
      interval: 1m
  valuesFrom:
  - kind: ConfigMap
    name: thanos-default
  - kind: ConfigMap
    name: thanos-environment
    optional: True
  - kind: ConfigMap
    name: thanos-site
    optional: True
  - kind: ConfigMap
    name: thanos-customer-default
    optional: True
  - kind: ConfigMap
    name: thanos-customer
    optional: True
  - kind: ConfigMap
    name: thanos-cluster
    optional: True