---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nfs-client-provisioner-management
  namespace: nfsstorage-system
spec:
  releaseName: management
  interval: 5m
  chart:
    spec:
      chart: nfs-client-provisioner
      version: '1.2.x'
      sourceRef:
        kind: HelmRepository
        name: stable
        namespace: schiff-system
      interval: 1m
  valuesFrom:
    - kind: ConfigMap
      name: nfs-client-provisioner-management-default
    - kind: ConfigMap
      name: nfs-client-provisioner-management-site
    - kind: ConfigMap
      name: nfs-client-provisioner-cluster
    - kind: ConfigMap
      name: nfs-client-provisioner-management-cluster
      optional: true
