---
apiVersion: v1
kind: ConfigMap
metadata:
  name: node-exporter-default
  namespace: kube-system
data:
  values.yaml: |
    serviceMonitor:
      enabled: true
      jobLabel: "app.kubernetes.io/name"
    service:
      addPrometheusScrapeAnnotation: false
    updateStrategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 2
    # This matches the taint of the master node
    # node-role.kubernetes.io/master:NoSchedule    
    tolerations:
    - key: "node-role.kubernetes.io/master"
      operator: "Exists"
      effect: "NoSchedule"
