---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-operator-default
  namespace: monitoring-system
data:
  values.yaml: |
    fullnameOverride: prometheus
    operator:
      enabled: true
    prometheus:
      enabled: false
    alertmanager:
      enabled: false
    exporters:
      enabled: false
      node-exporter:
        enabled: false
      kube-state-metrics:
        enabled: false
    coreDns:
      enabled: false
    kubeScheduler:
      enabled: false
    kubeApiServer:
      enabled: false
    kubeControllerManager:
      enabled: false
    kubeProxy:
      enabled: false
    kubelet:
      enabled: false