---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-default
  namespace: monitoring-system
data:
  values.yaml: |
    fullnameOverride: prometheus
    operator:
      enabled: false
    prometheus:
      enabled: true
      podDisruptionBudget:
        enabled: true
        minAvailable: 1
      ## How long to retain metrics
      ##
      retention: 20d

      replicaCount: 2

      externalLabels:
        ## Due To metric_name{label_name} restrictions we cannot use platform.das-schiff.io/label_name
        ## The conversion is as following:
        ## platform_customer -> platform.das-schiff.io/customer
        ## platform_fqdn is the unique infra handle for the cluster.
        platform_ci_id: ci/id# optional
        platform_alarm_type: virtual


      alertingEndpoints: 
        - namespace: monitoring-system
          name: alertmanager-alertmanager
          port: http
          pathPrefix: "/"

      thanos:
        create: true
        service:
          pullPolicy: IfNotPresent
          clusterIP: None
          port: 10901

      storageSpec: 
        emptyDir:
          medium: ""
        # volumeClaimTemplate:
        #   apiVersion: v1
        #   kind: PersistentVolumeClaim
        #   spec:
        #     accessModes:
        #     - ReadWriteOnce
        #     resources:
        #       requests:
        #         storage: 50Gi
        #     storageClassName: "<storage_class_name>"

    alertmanager:
      enabled: false
    exporters:
      enabled: false
      node-exporter:
        enabled: false
      kube-state-metrics:
        enabled: false
    coreDns:
      enabled: false
    ## :disabled: until it is available
    kubeScheduler:
      enabled: false
    kubeApiServer:
      enabled: true
    ## :disabled: until it is available
    kubeControllerManager:
      enabled: false
    ## :disabled: until it is available
    kubeProxy:
      enabled: false
    kubelet:
      enabled: true
      serviceMonitor:
        # Added relabeling to support Cluster Graph
        relabelings:
        - sourceLabels: ["__metrics_path__"]
          targetLabel: metrics_path
        cAdvisorRelabelings:
        - sourceLabels: ["__metrics_path__"]
          targetLabel: metrics_path