---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nfs-client-provisioner-customer-environment
  namespace: nfsstorage-system
data:
  values.yaml: |
    image:
      repository: harbor.das-schiff.io/gcr.io/k8s-staging-sig-storage/nfs-subdir-external-provisioner
      tag: v4.0.1
    resources:
      limits:
        cpu: 10m
        memory: 32Mi
      requests:
        cpu: 1m
        memory: 12Mi
