apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: schiff-operator
  name: schiff-operator-controller-manager
  namespace: engine-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: schiff-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: schiff-operator
    spec:
      containers:
      - args:
        - --secure-listen-address=0.0.0.0:8443
        - --upstream=http://127.0.0.1:8080/
        - --logtostderr=true
        - --v=10
        image: gcr.io/kubebuilder/kube-rbac-proxy:v0.5.0
        name: kube-rbac-proxy
        ports:
        - containerPort: 8443
          name: https
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
          requests:
            cpu: 10m
            memory: 20Mi
      - args:
        - --health-probe-bind-address=:8081
        - --metrics-bind-address=127.0.0.1:8080
        - --leader-elect
        command:
        - /manager
        image: harbor.das-schiff.telekom.de/schiff/schiff-operator:0.2.4
        envFrom:
          - secretRef:
              name: schiff-operator-config
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 50m
            memory: 20Mi
        securityContext:
          allowPrivilegeEscalation: false
      securityContext:
        runAsUser: 65532
      terminationGracePeriodSeconds: 10
      serviceAccountName: schiff-operator