apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: calico-kube-controllers
rules:
- apiGroups:
  - ''
  resources:
  - nodes
  verbs:
  - watch
  - list
  - get
- apiGroups:
  - ''
  resources:
  - pods
  verbs:
  - get
- apiGroups:
  - crd.projectcalico.org
  resources:
  - ippools
  verbs:
  - list
- apiGroups:
  - crd.projectcalico.org
  resources:
  - blockaffinities
  - ipamblocks
  - ipamhandles
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - watch
- apiGroups:
  - crd.projectcalico.org
  resources:
  - hostendpoints
  verbs:
  - get
  - list
  - create
  - update
  - delete
- apiGroups:
  - crd.projectcalico.org
  resources:
  - clusterinformations
  verbs:
  - get
  - create
  - update
- apiGroups:
  - crd.projectcalico.org
  resources:
  - kubecontrollersconfigurations
  verbs:
  - get
  - create
  - update
  - watch
