apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: components-providers-vsphere-ref
  namespace: schiff-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg-schiff
  interval: 5m
  path: ./providers/vsphere/ref
  prune: true
  sourceRef:
    kind: GitRepository
    name: components
  timeout: 2m
