apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: components-network-zones-m2m-default
  namespace: schiff-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg-schiff
  interval: 5m
  path: ./network-zones/m2m/default
  prune: false
  suspend: true
  sourceRef:
    kind: GitRepository
    name: components
  timeout: 2m
