---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: customer-components-clusters-f-refaws-customer-shortname-1
  namespace: schiff-system
spec:
  interval: 5m
  path: "./clusters/f/refaws/customer-shortname-1"
  prune: true
  sourceRef:
    kind: GitRepository
    name: customer-components
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg-schiff
  timeout: 2m