---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  releaseName: metallb
  interval: 5m
  dependsOn:
    - name: prometheus-operator
      namespace: monitoring-system
  chart:
    spec:
      chart: metallb
      version: '2.3.x'
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: schiff-system
      interval: 1m
  valuesFrom:
    - kind: ConfigMap
      name: metallb-default
    - kind: ConfigMap
      name: metallb-environment
      optional: true
    - kind: ConfigMap
      name: metallb-site
      optional: true
    - kind: ConfigMap
      name: metallb-cluster
      optional: true
