---
apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-cluster
  namespace: monitoring-system
data:
  values.yaml: |
    alertmanager:
      config:
        global:
          smtp_from: "alert.customer-shortname-1.refaws.f@das-schiff.io"
          smtp_hello: "alert.customer-shortname-1.refaws.f@das-schiff.io"
        receivers:
        - name: 'null'
        - name: 'platform'
          email_configs:
          - to: <mail>
            send_resolved: true
            headers:
              subject: '[alert.customer-shortname-1.refaws.f]|{{ template "__subject" . }}'
          - to: <mail>
            send_resolved: true
            headers:
              subject: '[alert.customer-shortname-1.refaws.f]|{{ template "__subject" . }}'
          - to: <mail>
            send_resolved: true
            headers:
              subject: '[alert.customer-shortname-1.refaws.f]|{{ template "__subject" . }}'
          - to: <mail>
            send_resolved: true
            headers:
              subject: '[alert.customer-shortname-1.refaws.f]|{{ template "__subject" . }}'
