---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-operator-cluster
  namespace: monitoring-system
data:
  values.yaml: |
    grafana:
      ingress:
        hostname: grafana.customer-shortname-1.refaws.f.das-schiff.io
