---
apiVersion: v1
kind: ConfigMap
metadata:
  name: metallb-cluster
  namespace: metallb-system
data:
  values.yaml: |
    configInline:
      peers:
      - peer-address: <ip:ip_address>
        peer-asn: <asn:int>
        my-asn: <asn:int>
      address-pools:
      - name: <management:str>
        protocol: bgp
        addresses:
        - <ip:ip_address>
      - name: <production:str>
        protocol: bgp
        addresses:
        -  <ip:ip_address>
        auto-assign: false
