---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-ingress-controller-management-cluster
  namespace: ingress-system
data:
  values.yaml: |
    service:
      annotations:
        metallb.universe.tf/allow-shared-ip: "<management:ip_address>/32"
      loadBalancerIP: "<management:ip_address>"
