---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: schiff-operator-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: schiff-operator-manager
subjects:
- kind: ServiceAccount
  name: schiff-operator
  namespace: engine-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: schiff-operator-proxy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: schiff-operator-proxy
subjects:
- kind: ServiceAccount
  name: schiff-operator
  namespace: engine-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: schiff-operator-manager
rules:
- apiGroups:
  - cluster.x-k8s.io
  resources:
  - machines
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - vspheremachines
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - vspheremachines/finalizers
  verbs:
  - update
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - vspheremachines/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: schiff-operator-metrics-reader
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: schiff-operator-proxy
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: schiff-operator
  name: schiff-operator-controller-manager
  namespace: engine-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: schiff-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: schiff-operator
    spec:
      containers:
      - args:
        - --secure-listen-address=0.0.0.0:8443
        - --upstream=http://127.0.0.1:8080/
        - --logtostderr=true
        - --v=10
        image: gcr.io/kubebuilder/kube-rbac-proxy:v0.5.0
        name: kube-rbac-proxy
        ports:
        - containerPort: 8443
          name: https
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
          requests:
            cpu: 10m
            memory: 20Mi
      - args:
        - --health-probe-bind-address=:8081
        - --metrics-bind-address=127.0.0.1:8080
        - --leader-elect
        command:
        - /manager
        image: dasschiff/schiff-operator:v0.2.5
        envFrom:
          - secretRef:
              name: schiff-operator-config
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 50m
            memory: 20Mi
        securityContext:
          allowPrivilegeEscalation: false
      securityContext:
        runAsUser: 65532
      terminationGracePeriodSeconds: 10
      serviceAccountName: schiff-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: schiff-operator-leader-election
  namespace: engine-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: schiff-operator-leader-election
subjects:
- kind: ServiceAccount
  name: schiff-operator
  namespace: engine-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: schiff-operator-leader-election
  namespace: engine-system
rules:
- apiGroups:
  - ""
  - coordination.k8s.io
  resources:
  - configmaps
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: v1
kind: Secret
metadata:
    name: schiff-operator-config
    namespace: engine-system
type: Opaque
stringData:
    IPAM_INFOBLOX_HOST: 10.10.10.10
    IPAM_INFOBLOX_WAPI_VERSION: 2.11.2
    IPAM_INFOBLOX_PORT: "443"
    IPAM_INFOBLOX_USERNAME: apiuser
    IPAM_INFOBLOX_PASSWORD: pwd
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: schiff-operator
  namespace: engine-system
---
apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: controller-manager
  name: schiff-operator-controller-manager-metrics
  namespace: engine-system
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    control-plane: controller-manager
