---
apiVersion: v1
kind: ConfigMap
metadata:
  name: metallb-environment
  namespace: metallb-system
data:
  values.yaml: |
    prometheusRule:
      enabled: true
    controller:
      prometheus:
        serviceMonitor:
          enabled: true
    speaker:
      prometheus:
        serviceMonitor:
          enabled: true	