---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-system
  labels:
    name: ingress-system
    platform.das-schiff.io/name: ingress-system
    owner: das-schiff
    platform.das-schiff.io/owner: das-schiff
