---
apiVersion: v1
kind: Namespace
metadata:
  name: kube-system
  labels:
    name: kube-system
    platform.das-schiff.io/name: kube-system
    owner: das-schiff
    platform.das-schiff.io/owner: das-schiff
