---
apiVersion: v1
kind: Namespace
metadata:
  name: kube-public
  labels:
    name: kube-public
    platform.das-schiff.io/name: kube-public
    owner: das-schiff
    platform.das-schiff.io/owner: das-schiff
