---
apiVersion: v1
kind: Namespace
metadata:
  name: metallb-system
  labels:
    name: metallb-system
    platform.das-schiff.io/name: metallb-system
    owner: das-schiff
    platform.das-schiff.io/owner: das-schiff
