apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: nfd
  namespace: schiff-system
spec:
  interval: 5m
  url: http://kubernetes-sigs.github.io/node-feature-discovery/charts
