---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    role: default
  name: alertmanager.alerts
  namespace: monitoring-system
spec:
  groups:
  - name: alertmanager.alerts
    rules:
    - alert: AlertmanagerConfigInconsistent
      annotations:
        message: The configuration of the instances of the Alertmanager cluster {{ $labels.service }} are out of sync.
      expr: |-
        (
          count_values("config_hash", alertmanager_config_hash{job="alertmanager",namespace="monitoring-system"}) by (service)
          /
          on(service) group_left() label_replace(
            max(
              prometheus_operator_spec_replicas{job="prometheus-operator",namespace="monitoring-system}", controller="alertmanager"}
            ) by (name, job, namespace, controller)
            , "service", "alertmanager-$1", "name", "(.*)"
          ) != 1
        )
      for: 5m
      labels:
        severity: Critical

    - alert: AlertmanagerFailedReload
      annotations:
        message: Reloading Alertmanager's configuration has failed for {{ $labels.namespace }}/{{ $labels.pod }}.
      expr: 'alertmanager_config_last_reload_successful{job="alertmanager",namespace="monitoring-system"} == 0'
      for: 10m
      labels:
        severity: Warning

    - alert: AlertmanagerMembersInconsistent
      annotations:
        message: Alertmanager has not found all other members of the cluster.
      expr: |-
        (
          alertmanager_cluster_members{job="alertmanager",namespace="monitoring-system"} 
          != 
          on (service) group_left() count by (service) (
            alertmanager_cluster_members{job="alertmanager", namespace="monitoring-system"}
          )
        )
      for: 5m
      labels:
        severity: Critical
