---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: customer-components-default
  namespace: schiff-system
spec:
  interval: 5m
  path: "./default"
  prune: true
  sourceRef:
    kind: GitRepository
    name: customer-components
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg-schiff
  timeout: 2m
