---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nfs-client-provisioner-customer
  namespace: nfsstorage-system
spec:
  releaseName: customer
  interval: 5m
  chart:
    spec:
      chart: nfs-subdir-external-provisioner
      version: '4.0.x'
      sourceRef:
        kind: HelmRepository
        name: nfs-subdir-external-provisioner
        namespace: schiff-system
      interval: 1m
  valuesFrom:
    - kind: ConfigMap
      name: nfs-client-provisioner-customer-default
    - kind: ConfigMap
      name: nfs-client-provisioner-customer-environment
      optional: true
    - kind: ConfigMap
      name: nfs-client-provisioner-customer-site
    - kind: ConfigMap
      name: nfs-client-provisioner-cluster
    - kind: ConfigMap
      name: nfs-client-provisioner-customer-cluster
      optional: true
